
GET http://localhost:8080/kafka/produce/hi vishnu
Accept: application/json
Content-Type: application/json

###


GET http://localhost:8080/kafka/health
Accept: application/json
Content-Type: application/json